# Generated by Django 3.1.2 on 2020-10-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidato',
            fields=[
                ('id_cadidato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=450, verbose_name='Nombre Completo')),
                ('foto', models.ImageField(upload_to='fotos/candidatos', verbose_name='Foto del Candidato')),
                ('partido', models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('MOVIMIENTO AL SOCIALISMO', 'MOVIMIENTO AL SOCIALISMO'), ('COMUNIDAD CIUDADANA', 'COMUNIDAD CIUDADANA'), ('CREEMOS', 'CREEMOS'), ('PARTIDO DEMOCRÁTICO CRISTIANO', 'PARTIDO DEMOCRÁTICO CRISTIANO'), ('LIBERTAR Y DEMOCRACIA', 'LIBERTAD Y DEMOCRACIA'), ('MOVIMIENTO TERCER SISTEMA', 'MOVIMIENTO TERCER SISTEMA'), ('PARTIDO DE ACCION NACIONAL BOLIVIANO', 'PARTIDO DE ACCION NACIONAL BOLIVIANO')], default=1, max_length=40, verbose_name='Partido Político')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('pdf', models.FileField(upload_to='pdf/candidatos', verbose_name='Plan de Gobierno')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidato',
            },
        ),
        migrations.CreateModel(
            name='votante',
            fields=[
                ('ci', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Carnet de identidad')),
                ('celular', models.CharField(max_length=7, verbose_name='Celular')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('candidato_favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diixweb.candidato', verbose_name='Candidato Favorito')),
            ],
            options={
                'verbose_name': 'Votante',
                'verbose_name_plural': 'Votantes',
                'db_table': 'votante',
            },
        ),
    ]
