# Generated by Django 3.1.2 on 2020-10-07 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diixweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='color',
            field=models.CharField(default=datetime.datetime(2020, 10, 7, 23, 56, 39, 195321, tzinfo=utc), max_length=10, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
